<?php
	include "configDB.inc.php";
	$fieldsSummary = array(
		"nom",
		"prenom",
		"grade",
		"unite",
		"type",
		"rapporteur",
		"date",
	);

	$fieldsAll = array(
		"nom" => "Nom",
		"prenom" => "Prenom",
		"grade" => "Grade",
		"unite" => "Unité",
		"type" => "Type",
		"rapporteur" => "Rapporteur",
		"prerapport" => "Points marquants",
		"anciennete_grade" => "Ancienneté dans grade",
		"date_recrutement" => "Date de recrutement",
		"production" => "Production scientifique",
		"production_notes" => "Production scientifique",
		"transfert" => "Transfert et valorisation",
		"transfert_notes" => "Détails transfert/valorisation",
		"encadrement" => "Encadrement",
		"encadrement_notes" => "Détails sur l'encadrement",
		"responsabilites" => "Responsabilités collectives",
		"responsabilites_notes" => "Détails responsabilités",
		"mobilite" => "Mobilité",
		"mobilite_notes" => "Détails sur la mobilité",
		"animation" => "Animation scientifique",
		"animation_notes" => "Détails sur l'animation",
		"rayonnement" => "Rayonnement",		
		"rayonnement_notes" => "Détails sur le rayonnement",		
		"rapport" => "Proposition de rapport",
		"avis" => "Proposition d'avis",
		"auteur" => "Auteur Dernière(s) modif(s)",
		"date" => "Date modification",
	);
	
	$examples = array(
		"nom" => "Doe",
		"prenom" => "John",
		"grade" => "DRCE",
		"unite" => "UMR 6666 (HELL)",
		"type" => "Promotion",
		"rapporteur" => "Anne ONYME",
		"prerapport" => "Candidat au fort potentiel, proche de la retraite ...",
		"anciennete_grade" => "~4 ans",
		"date_recrutement" => "1999",
		"production" => "A-",
		"production_notes" => "Nombreuses revues et conférences ...",
		"transfert" => "A",
		"transfert_notes" => "Un brevet et quelques logiciels diffusés ...",
		"encadrement" => "B",
		"encadrement_notes" => "Un étudiant en thèse, quelques stagiaires de M2 ...",
		"responsabilites" => "A+",
		"responsabilites_notes" => "Membre du comité national ...",
		"mobilite" => "C",
		"mobilite_notes" => "Peu de visites, en poste dans son labo de thèse ...",
		"animation" => "A+",
		"animation_notes" => "Jongle et joue de l'harmonica tout en présidant son GDR ...",
		"rayonnement" => "B+",		
		"rayonnement_notes" => "Travaux assez cités relativement aux pratiques de son domaine ...",		
		"rapport" => "La section 06 vous invite à renouveler votre garde robe. ..",
		"avis" => "Réservé",
		"auteur" => "joe",
		"date" => "3/02/2013",
	);

	$fieldsTypes = array(
		"nom" => "short",
		"prenom" => "short",
		"grade" => "short",
		"unite" => "short",
		"type" => "short",
		"rapporteur" => "short",
		"prerapport" => "long",
		"anciennete_grade" => "short",
		"date_recrutement" => "short",
		"production" => "short",
		"production_notes" => "long",
		"transfert" => "short",
		"transfert_notes" => "long",
		"encadrement" => "short",
		"encadrement_notes" => "long",
		"responsabilites" => "short",
		"responsabilites_notes" => "long",
		"mobilite" => "short",
		"mobilite_notes" => "long",
		"animation" => "short",
		"animation_notes" => "long",
		"rayonnement" => "short",		
		"rayonnement_notes" => "long",		
		"rapport" => "long",
		"avis" => "short",
		"auteur" => "short",
		"date" => "short",
	);
	
	$fieldsEdit = array(
		"id" => "Identifiant",
		"nom" => "Nom",
		"prenom" => "Prenom",
	);
	
	$typesEval = array(
		'Evaluation-Vague',
		'Evaluation-MiVague',
		'Promotion',
		'Candidature',
		'Suivi-PostEvaluation',
		'Titularisation',
		'ConfirmationAffectation',
	);
	
	$actions = array(
		'details' => "Détails", 
		'history' => "Historique", 
		'edit'  => "Modifier", 
	);
?>